#!/usr/bin/python3

def factors(file):
    with open(file, 'r') as f:
        lines = f.readlines()
        if not lines:
            print('There is no content in the file.')
            return
        for line in lines:
            try:
                n = int(line.strip())
                if n <= 0:
                    print("The provided value is not a non-negative integer.")
                    continue
                sqrt_n = int(n**0.5)
                for i in range(2, sqrt_n + 1):
                    if n % i == 0:
                        p, q = i, n // i
                        print(f'n={p}*{q}')
                        break
                else:
                    print(f'n is a prime number')
            except ValueError:
                print('The entered value is not a legitimate integer.')

factors('tests/test00')
