#!/usr/bin/python3

def factors(file):
    with open(file, 'r') as f:
        for line in f:
            n = int(line.strip())
            sqrt_n = int(n**0.5)
            for i in range(2, sqrt_n + 1):
                if n % i == 0:
                    p, q = i, n // i
                    print(f'n={p}*{q}')
                    break
            else:
                print(f'n is a prime number')

factors("tests/test00")
